### ISSUE TITLE
Verses from NUM.7.18 to b.NUM.7.23 in Amharic Bible are duplicated

### ISSUE THREAD

**Issue by morethanbooks** [christos-c/bible-corpus#15]
As title says, if I see it correctly, verses from NUM.7.18 to b.NUM.7.23 in Amharic Bible are duplicated. Of course, I don't read Amharic ;) but the ids are the same. When using xml:id attribute in TEI, it shows an error message.

Actually, it's the same with DEU.32.3., 2SA.17.1., 2KI9.3 and 2KI.14.20. Perhaps it would be better checking in general the ids of this Bible.

**Comment by christos-c** [comment]
Thanks for raising these. The issues with verse IDs reported here have been addressed.
