### ISSUE TITLE
Empty verses in Creole Bible

### ISSUE THREAD

**Issue by morethanbooks** [christos-c/bible-corpus#18]
This is not a formal error, but something strange: is it known that there are some verses without text in the Creole Bible? These verses:

- b.1CH.016.012
- b.1CH.008.008
- b.1CH.008.006
- b.1CH.004.034
- b.1CH.004.017
- b.GEN.020.017
- b.GEN.005.023

**Comment by christos-c** [comment]
This looks like the same issue as #20 - the verses are empty in the text (e.g. [1CH.16](https://www.stepbible.org/?q=version=KJV|version=Haitian|version=FreCrl|reference=1Chr.16&options=NVUGH&display=INTERLEAVED)).
