### ISSUE TITLE
Empty verses in English Web Bible

### ISSUE THREAD

**Issue by morethanbooks** [christos-c/bible-corpus#20]
In this Bible, there are 7 verses without text:

- b.LUK.017.036
- b.ACT.008.037
- b.ACT.015.034
- b.ACT.024.007
- b.ROM.016.025
- b.ROM.016.026
- b.ROM.016.027

**Comment by christos-c** [comment]
These are actually empty in the WEB text (e.g. [ACTS 15](https://www.stepbible.org/?q=version=KJV|version=WEB|reference=Acts.15&options=NVUGH&display=INTERLEAVED)), not sure if it's better to remove the verse `<seg>`s or leave them blank.

**Comment by morethanbooks** [comment]
Thanks for checking. I will leave them empty as they are right now. Perhaps state this somewhere in the header of the element to make document explicitly that you are aware of that.

**Comment by morethanbooks** [comment]
Yes, I guess that would be a good place. However, I am not completely sure.
