### ISSUE TITLE
Problem with Amharic file

### ISSUE THREAD

**Issue by rasoolims** [christos-c/bible-corpus#3]
Hi,

I created [a simple script](https://gist.github.com/rasoolims/992523c7aa191fe69b5a1a4a47fa9248) to create all pairs of aligned files (for Giza++ and other aligners). It seems that the Amharic file has problems (illegal XML characters in text).

Thanks

**Comment by christos-c** [comment]
Thanks for catching that @rasoolims. I have replaced the few '<<' and '>>' characters with ". I have also found some stray HTML markup at the end of some verses which I have removed.
Do you mind adding your script in my [Corpus Tools package](https://github.com/christos-c/bible-corpus-tools)? Right now I only have Java scripts and I know that a lot of researchers are more familiar with Python.
