### ISSUE TITLE
Errors in Bulgarian Bible

### ISSUE THREAD

**Issue by morethanbooks** [christos-c/bible-corpus#36]
There are a few problems in the Bulgarian Bible. There are a few verses with characters after the number of the verses:
-  b.NEH.12.47
- b.JOB.11.20
- b.ZEC.10.12
- b.MAT.26.75

Besides, b.JOH.1.1 is repeated.

**Comment by christos-c** [comment]
The issues with the IDs should be addressed in [8eeffea](https://github.com/christos-c/bible-corpus/commit/8eeffeafbf280143a788f8998db59cf86890c16d). Not sure if there were other issues with the IDs.

**Comment by morethanbooks** [comment]
I guess you know, but in the verse b.MAT.26.75 there is still the word `Тогава` in the id. That is the only verse which still has this issue

**Comment by christos-c** [comment]
Sorry @morethanbooks - not sure why, but this was left in my local repo without being pushed. This issue should be fixed now.
