### ISSUE TITLE
Shona.xml only has the first verse of Obediah

### ISSUE THREAD

**Issue by tkmunzwa** [christos-c/bible-corpus#4]
There is a single <seg> entry for Obediah in the Shona corpus - the rest are missing.

**Comment by christos-c** [comment]
@tkmunzwa, thanks for spotting this. Since this was a pull request from @sdini1, I would check with them in case the rest of the chapter is present somewhere. Otherwise, if you have a machine readable version of the chapter, I'm happy to add it.

**Comment by sdini1** [comment]
I'll get this sorted. cheers

**Comment by sdini1** [comment]
created a pull request for the rest of the book. cheers

**Comment by christos-c** [comment]
Thanks for the quick response @sdini1! @tkmunzwa I will close this issue, and create a new release of the corpus. Thank you both for your help.
