### ISSUE TITLE
Problem with the Estonian translations

### ISSUE THREAD

**Issue by rasoolims** [christos-c/bible-corpus#7]
Hi, 

There are numbers instead of real sentences in many Estonian translations; e.g.:

English:
```
<seg id="b.EXO.8.21" type="verse">
Else, if thou wilt not let my people go, behold, I will send swarms of flies upon thee, and upon thy servants, and upon thy people, and into thy houses: and the houses of the Egyptians shall be full of swarms of flies, and also the ground whereon they are.
</seg>
```

Estonian:
```
<seg id="b.EXO.8.21" type="verse">
21
</seg>
```

Greek
```
<seg id="b.EXO.8.21" type="verse">
διοτι εαν δεν εξαποστειλης τον λαον μου, ιδου, θελω στειλει επι σε και επι τους θεραποντας σου και επι τον λαον σου και επι τας οικιας σου κυνομυιαν, και αι οικιαι των Αιγυπτιων και η γη ετι επι της οποιας κατοικουσι θελουσι γεμισει απο κυνομυιαν
</seg>
```

**Comment by christos-c** [comment]
Hi @rasoolims. Unfortunately the source I used for the bible is no longer available, but the only other source I can find (http://gospelgo.com/u/estonian_nt.htm) seems to only have Genesis from the OT and no other chapter. 

Unless you have access to another machine-readable source for Estonian, I'm afraid the only thing I can do is to remove the missing chapters entirely and change its status (and filename) to PART.

**Comment by christos-c** [comment]
Removed the empty chapters and renamed the file as Estonian-PART.xml until a new translation source is found.
